# Generated by Django 3.0.8 on 2020-07-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20200716_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublishingHouse',
            new_name='Redaction',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publishing',
            new_name='redaction',
        ),
    ]
